This data is indexed to 2020

### Canada
Bank for International Settlements (2024), Effective exchange rates, BIS WS_EER 1.0 (data set), https://data.bis.org/topics/EER/BIS,WS_EER,1.0/M.R.N.CA (accessed on 11 October 2024).

### Italy
Bank for International Settlements (2024), Effective exchange rates, BIS WS_EER 1.0 (data set), https://data.bis.org/topics/EER/BIS,WS_EER,1.0/M.R.N.IT (accessed on 11 October 2024).

### France 
Bank for International Settlements (2024), Effective exchange rates, BIS WS_EER 1.0 (data set), https://data.bis.org/topics/EER/BIS,WS_EER,1.0/M.R.N.FR (accessed on 11 October 2024).

### Germany
Bank for International Settlements (2024), Effective exchange rates, BIS WS_EER 1.0 (data set), https://data.bis.org/topics/EER/BIS,WS_EER,1.0/M.R.N.DE (accessed on 12 October 2024).

### United Kingdom
Bank for International Settlements (2024), Effective exchange rates, BIS WS_EER 1.0 (data set), https://data.bis.org/topics/EER/BIS,WS_EER,1.0/M.R.N.GB (accessed on 12 October 2024).

### United States
Bank for International Settlements (2024), Effective exchange rates, BIS WS_EER 1.0 (data set), https://data.bis.org/topics/EER/BIS,WS_EER,1.0/M.R.N.US (accessed on 12 October 2024).

### Japan
Bank for International Settlements (2024), Effective exchange rates, BIS WS_EER 1.0 (data set), https://data.bis.org/topics/EER/BIS,WS_EER,1.0/M.R.N.JP (accessed on 12 October 2024).

In [20]:
import pandas as pd
import numpy as np

In [21]:
canada_df = pd.read_csv("data/exchange-rates/canada-exchange-rate.csv", skiprows=3)
france_df = pd.read_csv("data/exchange-rates/france-exchange-rate.csv", skiprows=3)
germany_df = pd.read_csv("data/exchange-rates/germany-exchange-rate.csv", skiprows=3)
italy_df = pd.read_csv("data/exchange-rates/italy-exchange-rate.csv", skiprows=3)
uk_df = pd.read_csv("data/exchange-rates/uk-exchange-rate.csv", skiprows=3)
usa_df = pd.read_csv("data/exchange-rates/usa-exchange-rate.csv", skiprows=3)
japan_df = pd.read_csv("data/exchange-rates/japan-exchange-rate.csv", skiprows=3)

In [22]:
canada_df

,DATAFLOW_ID:Dataflow ID,KEY:Timeseries Key,FREQ:Frequency,EER_TYPE:Type,EER_BASKET:Basket,REF_AREA:Reference area,Unit,Unit multiplier,TIME_PERIOD:Period,OBS_CONF:Confidentiality,OBS_PRE_BREAK:Pre-break value,OBS_STATUS:Status,OBS_VALUE:Value
0,"BIS,WS_EER,1.0",M.R.N.CA,M:Monthly,R:Real,N:Narrow (27 economies),CA:Canada,"Index, 2020 = 100",NaN,1964-01-31,F:Free,NaN,A:Normal value,132.44
1,"BIS,WS_EER,1.0",M.R.N.CA,M:Monthly,R:Real,N:Narrow (27 economies),CA:Canada,"Index, 2020 = 100",NaN,1964-02-29,F:Free,NaN,A:Normal value,132.29
2,"BIS,WS_EER,1.0",M.R.N.CA,M:Monthly,R:Real,N:Narrow (27 economies),CA:Canada,"Index, 2020 = 100",NaN,1964-03-31,F:Free,NaN,A:Normal value,132.17
3,"BIS,WS_EER,1.0",M.R.N.CA,M:Monthly,R:Real,N:Narrow (27 economies),CA:Canada,"Index, 2020 = 100",NaN,1964-04-30,F:Free,NaN,A:Normal value,132.71
4,"BIS,WS_EER,1.0",M.R.N.CA,M:Monthly,R:Real,N:Narrow (27 economies),CA:Canada,"Index, 2020 = 100",NaN,1964-05-31,F:Free,NaN,A:Normal value,134.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...
723,"BIS,WS_EER,1.0",M.R.N.CA,M:Monthly,R:Real,N:Narrow (27 economies),CA:Canada,"Index, 2020 = 100",NaN,2024-04-30,F:Free,NaN,A:Normal value,96.78
724,"BIS,WS_EER,1.0",M.R.N.CA,M:Monthly,R:Real,N:Narrow (27 economies),CA:Canada,"Index, 2020 = 100",NaN,2024-05-31,F:Free,NaN,A:Normal value,97.03
725,"BIS,WS_EER,1.0",M.R.N.CA,M:Monthly,R:Real,N:Narrow (27 economies),CA:Canada,"Index, 2020 = 100",NaN,2024-06-30,F:Free,NaN,A:Normal value,97.20
726,"BIS,WS_EER,1.0",M.R.N.CA,M:Monthly,R:Real,N:Narrow (27 economies),CA:Canada,"Index, 2020 = 100",NaN,2024-07-31,F:Free,NaN,A:Normal value,97.32
727,"BIS,WS_EER,1.0",M.R.N.CA,M:Monthly,R:Real,N:Narrow (27 economies),CA:Canada,"Index, 2020 = 100",NaN,2024-08-31,F:Free,NaN,A:Normal value,97.65

In [23]:
canada_df = canada_df[["TIME_PERIOD:Period", "OBS_VALUE:Value", "Unit"]]
italy_df = italy_df[["TIME_PERIOD:Period", "OBS_VALUE:Value", "Unit"]]
france_df = france_df[["TIME_PERIOD:Period", "OBS_VALUE:Value", "Unit"]]
germany_df = germany_df[["TIME_PERIOD:Period", "OBS_VALUE:Value", "Unit"]]
uk_df = uk_df[["TIME_PERIOD:Period", "OBS_VALUE:Value", "Unit"]]
usa_df = usa_df[["TIME_PERIOD:Period", "OBS_VALUE:Value", "Unit"]]
japan_df = japan_df[["TIME_PERIOD:Period", "OBS_VALUE:Value", "Unit"]]

In [24]:
df_list = [canada_df, italy_df, france_df, germany_df, uk_df, usa_df, japan_df]

In [26]:
for country in df_list:
    country['TIME_PERIOD:Period'] = pd.to_datetime(country['TIME_PERIOD:Period'], format= "%Y-%m-%d")
    country['TIME_PERIOD:Period'] = country['TIME_PERIOD:Period'].dt.strftime("%Y-%m")
    country.rename(columns={'TIME_PERIOD:Period': "TIME_PERIOD", "OBS_VALUE:Value": "exchange_rate"}, inplace=True)

/var/folders/sh/s_xv2d8x6kv1_qyc9qgmkv300000gn/T/ipykernel_7821/2335832785.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  country['TIME_PERIOD:Period'] = pd.to_datetime(country['TIME_PERIOD:Period'], format= "%Y-%m-%d")
/var/folders/sh/s_xv2d8x6kv1_qyc9qgmkv300000gn/T/ipykernel_7821/2335832785.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  country['TIME_PERIOD:Period'] = country['TIME_PERIOD:Period'].dt.strftime("%Y-%m")
/var/folders/sh/s_xv2d8x6kv1_qyc9qgmkv300000gn/T/ipykernel_7821/2335832785.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  country.rename(columns={'TIME_PERIOD:Period': "TIME_PERIOD", "OBS_VALUE:Value": "exchange_rate"}, inplace=True)

In [27]:
canada_df

    TIME_PERIOD  exchange_rate               Unit
0       1964-01         132.44  Index, 2020 = 100
1       1964-02         132.29  Index, 2020 = 100
2       1964-03         132.17  Index, 2020 = 100
3       1964-04         132.71  Index, 2020 = 100
4       1964-05         134.07  Index, 2020 = 100
..          ...            ...                ...
723     2024-04          96.78  Index, 2020 = 100
724     2024-05          97.03  Index, 2020 = 100
725     2024-06          97.20  Index, 2020 = 100
726     2024-07          97.32  Index, 2020 = 100
727     2024-08          97.65  Index, 2020 = 100

[728 rows x 3 columns]

In [28]:
japan_df

    TIME_PERIOD  exchange_rate               Unit
0       1964-01          56.84  Index, 2020 = 100
1       1964-02          56.41  Index, 2020 = 100
2       1964-03          56.40  Index, 2020 = 100
3       1964-04          56.94  Index, 2020 = 100
4       1964-05          60.09  Index, 2020 = 100
..          ...            ...                ...
723     2024-04          65.71  Index, 2020 = 100
724     2024-05          64.68  Index, 2020 = 100
725     2024-06          64.19  Index, 2020 = 100
726     2024-07          64.22  Index, 2020 = 100
727     2024-08          68.70  Index, 2020 = 100

[728 rows x 3 columns]